### ISSUE TITLE
Strange behavior when trying to invert integer matrices

### ISSUE THREAD

**Issue by wlevine** [SciRuby/nmatrix#386]
The behavior depends on whether has_clapack? is true or false:
```
> NMatrix.has_clapack?
=> true
> a = N[[1,2],[3,4]]
=> 
[
  [1, 2]   [3, 4] ]
> a.invert!
DataTypeError: this matrix operation undefined for integer matrices
from /home/will/src/nmatrix/lib/nmatrix/math.rb:142:in `clapack_getrf'
> a.invert
DataTypeError: this matrix operation undefined for integer matrices
from /home/will/src/nmatrix/lib/nmatrix/math.rb:142:in `clapack_getrf'
```
If false:
```
> NMatrix.has_clapack?
=> false
> a = N[[1,2],[3,4]]
=> 
[
  [1, 2]   [3, 4] ]
> a.invert!
=> 
[
  [-1, 0]   [ 1, 0] ]
> a = N[[1,2],[3,4]]
=> 
[
  [1, 2]   [3, 4] ]
> a.invert
=> 
[
  [-1.9999999999999996,   0.9999999999999998]
  [ 1.4999999999999998, -0.49999999999999994]
]
```
I assume the correct behavior is to throw an error if `#invert!` is called and return a floating-point matrix if `#invert` is called.

**Comment by wlevine** [comment]
Fixed in #393. Now we raise an error if `#invert!` is called on a integer matrix and return a floating-point matrix if `#invert` is called on a integer matrix.
