### ISSUE TITLE
Passing array of arrays as shape leads to bad output

### ISSUE THREAD

**Issue by v0dro** [SciRuby/nmatrix#420]
This is the result when passing the `shape` argument of the `.zeroes` function as `[[3]]`:

``` ruby

a=NMatrix.zeroes([[3]], dtype: :complex128)
# => #<NMatrix:0x8669998 shape:[70470990] dtype:complex128 stype:dense>
```

It also leads to a segmentation fault sometimes if the shape turns out to be TOO big.

**Comment by mohawkjohn** [comment]
Good catch.

**Comment by lokeshh** [comment]
Running the above code give me the following error:

    [10] pry(main)> a=NMatrix.zeroes([[3]], dtype: :complex128)
    TypeError: no implicit conversion of Array into Integer
    from /home/ubuntu/workspace/nmatrix/lib/nmatrix/shortcuts.rb:147:in `initialize'

What could be the problem?

**Comment by mohawkjohn** [comment]
It's because you have double brackets (which is the bug @v0dro was highlighting). For correct functionality, you want one of these:

    a = NMatrix.zeroes([3], dtype: :complex128)
    a = NMatrix.zeroes([3,1], dtype: :complex128)
    a = NMatrix.zeroes([1,3], dtype: :complex128)

**Comment by lokeshh** [comment]
So, what should be correct behavior?

**Comment by mohawkjohn** [comment]
You shouldn't enter `[[3]]`. It's nonsensical. But NMatrix should be checking to make sure the first entry in the array is a Fixnum.

**Comment by lokeshh** [comment]
>But NMatrix should be checking to make sure the first entry in the array is a Fixnum.

I don't think I get what you saying. Kindly explain to me given [[3]] is nonsensical, what's the point of checking for it?

Even if we introduce check for this function `zeros`, what about other functions?

There are other function which could give the same error. For example:

```ruby
[32] pry(main)> NMatrix.diag([[[3]]])
TypeError: no implicit conversion of Array into Integer
from /home/ubuntu/workspace/nmatrix/lib/nmatrix/shortcuts.rb:271:in `[]='
```

**Comment by mohawkjohn** [comment]
I'm not really sure what you're asking. We check for lots of user input that is nonsensical because those nonsensical inputs cause unpredictable behavior (such as segmentation faults).

You don't have to include the check in zeros. Zeros just calls the regular constructor, which is written in C, which itself calls a function which interprets the shape argument. We only need to modify that shape interpretation function.

**Comment by lokeshh** [comment]
Ok. The point of confusion here is that I am not getting unpredictable behaviour at all. I am getting a TypeError every time I pass an invalid shape argument.

**Comment by v0dro** [comment]
Ok that's weird.

What version are you using? Can you freshly clone nmatrix from sciruby and try it out?

**Comment by lokeshh** [comment]
I forked the repository https://github.com/SciRuby/nmatrix to https://github.com/lokeshh/nmatrix. Then I cloned it into my computer. I did `bundle install`, then `bundle exec rake compile`, then `bundle exec rake spec`. 

Then on the console which I got by executing `bundle exec rake pry`, I got the same output as earlier:

```ruby
https://github.com/lokeshh/nmatrix
```

**Comment by mohawkjohn** [comment]
Oh, I get what you're saying now. Yes, on Ruby 2.2.2 I get the same output as @lokeshh.

**Comment by v0dro** [comment]
I'm using 2.2.1. Don't know what's causing this :\

**Comment by mohawkjohn** [comment]
Are you running it in pry, @v0dro?

**Comment by v0dro** [comment]
Yep. Still the same.

**Comment by mohawkjohn** [comment]
I hate to ask you to install a new Ruby, but does it happen with 2.2.2? I'd like to try to isolate it.

**Comment by wlevine** [comment]
One could make a spec and run it on travis to see which versions it works on.

**Comment by lokeshh** [comment]
I installed Ruby 2.2.1 via rmv. The output is still the same for me like earlier. I even recompiled using `rake compile`.

**Comment by mohawkjohn** [comment]
@v0dro Does the behavior persist if you totally erase your build files and re-build?

**Comment by v0dro** [comment]
Just give me some time to reproduce this one.

I'm currently working on the FFTW extension and don't want anything that might break my build.

**Comment by GauravTamba** [comment]
Hi, I just tried this out too and I got the TypeError in pry and irb as well. I'm using Ruby 2.2.2 with a fresh install of everything.

**Comment by NakulVaidya** [comment]
I got the bug. I have started working on it.
