### ISSUE TITLE
Unable to install nmatrix gem on Ubuntu 14.04

### ISSUE THREAD

**Issue by sudk1896** [SciRuby/nmatrix#559]
Hello,
I have been trying to install the nmatrix gem via `sudo gem install nmatrix` but have been unsuccessful. I have tried searching for fixes but to no avail.
The error message is 
```
Building native extensions.  This could take a while...
ERROR:  Error installing nmatrix:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
using C++ standard... c++11
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby1.9.1
/var/lib/gems/1.9.1/gems/nmatrix-0.2.3/lib/nmatrix/mkmf.rb:91:in `<top (required)>': undefined method `+' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:28:in `<main>'
g++ reports version... 4.8.4-2ubuntu1~14.04.3)


Gem files will remain installed in /var/lib/gems/1.9.1/gems/nmatrix-0.2.3 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/nmatrix-0.2.3/ext/nmatrix/gem_make.out
```
My g++ version - ```g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4```
I am doing a normal install that is mentioned in the wiki and not the one with the headers ```ATLAS``` or  ```LAPACK```.
Any help would be appreciated.

**Comment by sudk1896** [comment]
Apologies, I had an older version of ruby. I have fixed this issue by installing the latest stable one.
I am closing this.
