### ISSUE TITLE
lib/nmatrix/nmatrix.rb:47:in `require_relative': superclass mismatch for class NMatrix (TypeError)

### ISSUE THREAD

**Issue by jedld** [SciRuby/nmatrix#628]
ruby version: 2.6.3
system: ubuntu
nmatrix version: 0.2.4

Just requiring nmaxtrix results in:

       3: from /home/jedld/.rvm/gems/ruby-2.6.3@grabai/gems/nmatrix-0.2.4/lib/nmatrix.rb:28:in `<top (required)>'
        2: from /home/jedld/.rvm/gems/ruby-2.6.3@grabai/gems/nmatrix-0.2.4/lib/nmatrix.rb:28:in `require'
        1: from /home/jedld/.rvm/gems/ruby-2.6.3@grabai/gems/nmatrix-0.2.4/lib/nmatrix/nmatrix.rb:47:in `<top (required)>'
/home/jedld/.rvm/gems/ruby-2.6.3@grabai/gems/nmatrix-0.2.4/lib/nmatrix/nmatrix.rb:47:in `require_relative': superclass mismatch for class NMatrix (TypeError)

**Comment by jedld** [comment]
looks like a conflict when using narray
